POST http://localhost:4000/api/transactions
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZjcwYWViZjg0NWQyNzEzZTI0OTZmYSIsInVzZXJuYW1lIjoiTWFudWVsIiwiaWF0IjoxNjYwMzYyNTIyfQ.bDF75qMJo44Tb3ywKfoNwQYtZgh5_IuspAvSfbkR5OU

 {
    "accountOriginAlias": "cuentamanuu",
    "accountDestinationAlias" : "cuentamanu",
    "amount": "10"
  }